
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Julien de Alma",
  description: "Generated by Noxosite",
};

export default function Home() {
  return (
    <main className="min-h-screen bg-black text-white font-sans antialiased">
         
         <div id="header" dangerouslySetInnerHTML={{ __html: `<header class="sticky top-0 z-50 backdrop-blur-xl bg-neutral-950/80 border-b border-white/5 font-serif">
  <nav class="container mx-auto px-6 h-24 flex items-center justify-between">
    <!-- Brand Logo -->
    <div class="flex-shrink-0">
      <a href="/" class="group relative">
        <span class="text-2xl md:text-3xl font-bold tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-[#ba34d5] to-[#33e1b5] transition-all duration-500 group-hover:opacity-80">
          Julien de Alma
        </span>
        <div class="absolute -bottom-1 left-0 w-0 h-px bg-gradient-to-r from-[#ba34d5] to-[#33e1b5] transition-all duration-500 group-hover:w-full"></div>
      </a>
    </div>

    <!-- Navigation Links -->
    <div class="hidden lg:flex items-center gap-12">
      <a href="#ingenieur" class="group relative text-sm uppercase tracking-[0.2em] text-white/70 hover:text-white transition-colors">
        L'Ingénieur
        <span class="block max-w-0 group-hover:max-w-full transition-all duration-500 h-0.5 bg-[#ba34d5]"></span>
      </a>
      <a href="#scientifique" class="group relative text-sm uppercase tracking-[0.2em] text-white/70 hover:text-white transition-colors">
        Le Scientifique
        <span class="block max-w-0 group-hover:max-w-full transition-all duration-500 h-0.5 bg-[#33e1b5]"></span>
      </a>
      <a href="#spirituel" class="group relative text-sm uppercase tracking-[0.2em] text-white/70 hover:text-white transition-colors">
        Le Spirituel
        <span class="block max-w-0 group-hover:max-w-full transition-all duration-500 h-0.5 bg-white"></span>
      </a>
    </div>

    <!-- Actions -->
    <div class="flex items-center gap-6">
      <a href="#scan" class="relative inline-flex items-center justify-center px-8 py-3.5 overflow-hidden font-medium tracking-tighter text-white bg-neutral-900 rounded-full group">
        <span class="absolute w-0 h-0 transition-all duration-500 ease-out bg-gradient-to-r from-[#ba34d5] to-[#33e1b5] rounded-full group-hover:w-56 group-hover:h-56"></span>
        <span class="absolute inset-0 w-full h-full -mt-1 rounded-lg opacity-30 bg-gradient-to-b from-transparent via-transparent to-neutral-700"></span>
        <span class="relative text-xs uppercase tracking-widest">Scan de Cohérence</span>
      </a>
      
      <!-- Mobile Menu Button -->
      <button class="lg:hidden text-white hover:text-[#33e1b5] transition-colors">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M4 6h16M4 12h16m-7 6h7" />
        </svg>
      </button>
    </div>
  </nav>
</header>` }} />
         

         <div id="hero" dangerouslySetInnerHTML={{ __html: `<section class='relative min-h-screen bg-neutral-950 text-white overflow-hidden font-serif selection:bg-[#ba34d5]/30'>
  <!-- Navbar -->
  <header class='fixed top-0 w-full z-50 backdrop-blur-md bg-black/50 border-b border-white/5'>
    <nav class='container mx-auto px-6 h-20 flex items-center justify-between'>
      <div class='text-2xl font-bold tracking-tighter'>
        <span class='text-transparent bg-clip-text bg-gradient-to-r from-[#ba34d5] to-[#33e1b5]'>JULIEN DE ALMA</span>
      </div>
      <div class='hidden md:flex items-center space-x-10 text-sm tracking-widest uppercase font-sans text-slate-300'>
        <a href='#' class='hover:text-white transition-colors'>L'Approche</a>
        <a href='#' class='hover:text-white transition-colors'>L'Alchimie</a>
        <a href='#' class='px-6 py-2 border border-white/20 rounded-full hover:bg-white hover:text-black transition-all duration-300'>Réserver un Appel</a>
      </div>
    </nav>
  </header>

  <!-- Abstract Background Orbs -->
  <div class='absolute top-[-10%] left-[-10%] w-[500px] h-[500px] bg-[#ba34d5]/20 rounded-full blur-[120px] pointer-events-none'></div>
  <div class='absolute bottom-[-10%] right-[-10%] w-[600px] h-[600px] bg-[#33e1b5]/10 rounded-full blur-[150px] pointer-events-none'></div>

  <div class='container mx-auto px-6 pt-40 pb-32 relative z-10'>
    <div class='max-w-5xl mx-auto text-center'>
      <!-- Top Badge -->
      <div class='inline-block px-4 py-1 mb-8 border border-[#33e1b5]/30 rounded-full bg-[#33e1b5]/5 backdrop-blur-sm'>
        <span class='text-[#33e1b5] text-xs uppercase tracking-[0.2em] font-sans font-semibold'>Ingénierie • Science • Spiritualité</span>
      </div>
      
      <h1 class='text-5xl md:text-7xl lg:text-8xl font-medium leading-[1.1] mb-8'>
        Transmutez votre chaos opérationnel en <span class='text-transparent bg-clip-text bg-gradient-to-r from-[#ba34d5] to-[#33e1b5]'>algorithme de haute fréquence</span>
      </h1>

      <p class='text-xl md:text-2xl text-slate-400 max-w-3xl mx-auto mb-12 font-sans font-light leading-relaxed'>
        Une fusion unique entre l'ingénierie, la science et la spiritualité pour faire de votre entreprise le prolongement fluide de votre conscience.
      </p>

      <div class='flex flex-col sm:flex-row items-center justify-center gap-6'>
        <button class='group relative px-10 py-5 bg-gradient-to-r from-[#ba34d5] to-[#33e1b5] rounded-full font-sans font-bold text-lg hover:shadow-[0_0_40px_rgba(186,52,213,0.4)] transition-all duration-500'>
          Activer la Transformation
        </button>
        <button class='px-10 py-5 bg-white/5 border border-white/10 rounded-full font-sans font-semibold text-lg hover:bg-white/10 transition-all'>
          Découvrir la Méthode
        </button>
      </div>
    </div>

    <!-- Features/Pillars Grid -->
    <div class='grid grid-cols-1 md:grid-cols-3 gap-8 mt-32'>
      <div class='group p-8 rounded-3xl bg-white/5 border border-white/10 backdrop-blur-xl hover:border-[#ba34d5]/50 transition-all duration-500'>
        <div class='w-12 h-12 mb-6 flex items-center justify-center rounded-2xl bg-gradient-to-br from-[#ba34d5] to-[#ba34d5]/20'>
          <svg class='w-6 h-6 text-white' fill='none' stroke='currentColor' viewBox='0 0 24 24'><path stroke-linecap='round' stroke-linejoin='round' stroke-width='1.5' d='M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4'></path></svg>
        </div>
        <h3 class='text-2xl mb-4 font-semibold'>L'Ingénieur</h3>
        <p class='text-slate-400 font-sans leading-relaxed'>Nettoyage du "legacy code" de vos systèmes pour supprimer définitivement la friction technique et opérationnelle.</p>
      </div>

      <div class='group p-8 rounded-3xl bg-white/5 border border-white/10 backdrop-blur-xl hover:border-[#33e1b5]/50 transition-all duration-500 translate-y-4'>
        <div class='w-12 h-12 mb-6 flex items-center justify-center rounded-2xl bg-gradient-to-br from-[#33e1b5] to-[#33e1b5]/20'>
          <svg class='w-6 h-6 text-white' fill='none' stroke='currentColor' viewBox='0 0 24 24'><path stroke-linecap='round' stroke-linejoin='round' stroke-width='1.5' d='M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z'></path></svg>
        </div>
        <h3 class='text-2xl mb-4 font-semibold'>Le Scientifique</h3>
        <p class='text-slate-400 font-sans leading-relaxed'>Remplacement de l'intuition floue par une lecture rigoureuse des patterns et des probabilités de succès.</p>
      </div>

      <div class='group p-8 rounded-3xl bg-white/5 border border-white/10 backdrop-blur-xl hover:border-[#ba34d5]/50 transition-all duration-500'>
        <div class='w-12 h-12 mb-6 flex items-center justify-center rounded-2xl bg-gradient-to-br from-[#ba34d5] to-[#33e1b5]'>
          <svg class='w-6 h-6 text-white' fill='none' stroke='currentColor' viewBox='0 0 24 24'><path stroke-linecap='round' stroke-linejoin='round' stroke-width='1.5' d='M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z'></path></svg>
        </div>
        <h3 class='text-2xl mb-4 font-semibold'>Le Spirituel</h3>
        <p class='text-slate-400 font-sans leading-relaxed'>Alignement du moteur de croissance sur votre intention pure pour éviter le burn-out de l'âme.</p>
      </div>
    </div>
  </div>

  <!-- Scrolling text decor -->
  <div class='absolute bottom-10 left-0 w-full whitespace-nowrap opacity-[0.03] select-none pointer-events-none'>
    <div class='text-[10rem] font-bold uppercase'>ALGORITHME • CONSCIENCE • FLUIDITÉ • PRÉCISION • SENS • ÉNERGIE</div>
  </div>
</section>` }} />
         

         <div id="features" dangerouslySetInnerHTML={{ __html: `<section class="relative bg-neutral-950 py-32 lg:py-48 overflow-hidden font-['Playfair_Display']">
  <!-- Background Ambient Glow -->
  <div class="absolute top-0 left-1/4 w-96 h-96 bg-[#ba34d5]/10 rounded-full blur-[120px]"></div>
  <div class="absolute bottom-0 right-1/4 w-96 h-96 bg-[#33e1b5]/10 rounded-full blur-[120px]"></div>

  <div class="container mx-auto px-6 relative z-10">
    <div class="max-w-4xl mb-24">
      <h2 class="text-4xl md:text-6xl font-bold text-white leading-tight mb-8">
        Les <span class="text-transparent bg-clip-text bg-gradient-to-r from-[#ba34d5] to-[#33e1b5]">'Bugs'</span> de votre <br/>Système d'Exploitation
      </h2>
      <p class="text-xl text-neutral-400 max-w-2xl leading-relaxed">
        Avant de bâtir votre empire, nous devons purger les erreurs de code héritées. Votre entreprise n'est pas limitée par le marché, mais par les processus archaïques qui tournent en tâche de fond dans votre psyché.
      </p>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
      <!-- Feature Card 1: L'Architecture Obsolète -->
      <div class="group relative p-8 md:p-10 rounded-3xl bg-white/5 border border-white/10 backdrop-blur-xl hover:border-[#ba34d5]/40 transition-all duration-500">
        <div class="mb-8 inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-gradient-to-br from-[#ba34d5]/20 to-transparent border border-[#ba34d5]/30">
          <svg class="w-8 h-8 text-[#ba34d5]" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"></path>
          </svg>
        </div>
        <h3 class="text-2xl font-bold text-white mb-4">L'Architecture Obsolète</h3>
        <p class="text-neutral-400 leading-relaxed mb-6">
          La <span class="text-white italic">"Prison Dorée"</span> : vous opérez sur un Legacy Code hérité de vos débuts. Ce qui vous a permis de réussir hier est devenu le plafond de verre qui bride votre expansion aujourd'hui.
        </p>
        <div class="h-1 w-0 group-hover:w-full bg-gradient-to-r from-[#ba34d5] to-[#33e1b5] transition-all duration-700"></div>
      </div>

      <!-- Feature Card 2: La Dette Émotionnelle -->
      <div class="group relative p-8 md:p-10 rounded-3xl bg-white/5 border border-white/10 backdrop-blur-xl hover:border-[#33e1b5]/40 transition-all duration-500 mt-0 md:mt-12">
        <div class="mb-8 inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-gradient-to-br from-[#33e1b5]/20 to-transparent border border-[#33e1b5]/30">
          <svg class="w-8 h-8 text-[#33e1b5]" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M13 10V3L4 14h7v7l9-11h-7z"></path>
          </svg>
        </div>
        <h3 class="text-2xl font-bold text-white mb-4">La Dette Émotionnelle</h3>
        <p class="text-neutral-400 leading-relaxed mb-6">
          Des <span class="text-white italic">tâches de fond énergivores</span> saturent votre RAM mentale. Vos peurs non résolues et vos doutes inconscients pompent l'énergie nécessaire à votre génie créatif, menant au burn-out de l'âme.
        </p>
        <div class="h-1 w-0 group-hover:w-full bg-gradient-to-r from-[#33e1b5] to-[#ba34d5] transition-all duration-700"></div>
      </div>

      <!-- Feature Card 3: L'Erreur de Compilation -->
      <div class="group relative p-8 md:p-10 rounded-3xl bg-white/5 border border-white/10 backdrop-blur-xl hover:border-[#ba34d5]/40 transition-all duration-500">
        <div class="mb-8 inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-gradient-to-br from-[#ba34d5]/20 to-transparent border border-[#ba34d5]/30">
          <svg class="w-8 h-8 text-[#ba34d5]" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path>
          </svg>
        </div>
        <h3 class="text-2xl font-bold text-white mb-4">L'Erreur de Compilation</h3>
        <p class="text-neutral-400 leading-relaxed mb-6">
          Le <span class="text-white italic">désalignement de la vision</span>. Quand vos actions quotidiennes ne sont plus le prolongement de votre conscience pure, le système entre en conflit interne. La clarté disparaît, le chaos s'installe.
        </p>
        <div class="h-1 w-0 group-hover:w-full bg-gradient-to-r from-[#ba34d5] to-[#33e1b5] transition-all duration-700"></div>
      </div>
    </div>

    <div class="mt-24 text-center">
      <div class="inline-block p-[1px] rounded-full bg-gradient-to-r from-[#ba34d5] to-[#33e1b5]">
        <button class="px-10 py-4 bg-neutral-950 rounded-full text-white font-semibold hover:bg-transparent transition-all duration-300">
          Réinitialiser mon système
        </button>
      </div>
    </div>
  </div>
</section>` }} />
         

         <div id="about" dangerouslySetInnerHTML={{ __html: `<section id='about' class='relative py-32 md:py-40 bg-neutral-950 overflow-hidden font-playfair'>
  <div class='absolute top-0 right-0 -translate-y-1/2 translate-x-1/2 w-[600px] h-[600px] bg-[#ba34d5]/10 rounded-full blur-[120px]'></div>
  <div class='absolute bottom-0 left-0 translate-y-1/2 -translate-x-1/2 w-[500px] h-[500px] bg-[#33e1b5]/10 rounded-full blur-[120px]'></div>

  <div class='container mx-auto px-6 relative z-10'>
    <div class='grid grid-cols-1 lg:grid-cols-12 gap-16 items-start'>
      
      <!-- Visual Column -->
      <div class='lg:col-span-5 relative group'>
        <div class='absolute -inset-1 bg-gradient-to-br from-[#ba34d5] to-[#33e1b5] rounded-3xl blur opacity-25 group-hover:opacity-40 transition duration-1000'></div>
        <div class='relative aspect-[4/5] bg-neutral-900 rounded-2xl overflow-hidden border border-white/10'>
          <div class='absolute inset-0 bg-gradient-to-t from-neutral-950 via-transparent to-transparent z-10'></div>
          <div class='absolute bottom-8 left-8 right-8 z-20'>
            <p class='text-[#33e1b5] font-mono text-sm tracking-widest mb-2'>ARCHITECTURE SYSTÈME</p>
            <h3 class='text-white text-3xl font-bold'>Julien de Alma</h3>
            <div class='w-12 h-1 bg-gradient-to-r from-[#ba34d5] to-[#33e1b5] mt-4'></div>
          </div>
          <!-- Placeholder for portrait/visual -->
          <div class='flex items-center justify-center h-full text-white/10'>
            <svg class='w-32 h-32' fill='currentColor' viewBox='0 0 24 24'><path d='M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5'></path></svg>
          </div>
        </div>
      </div>

      <!-- Content Column -->
      <div class='lg:col-span-7 flex flex-col justify-center'>
        <h2 class='text-4xl md:text-6xl font-bold text-white leading-tight mb-8'>
          Julien de Alma : <br/>
          <span class='text-transparent bg-clip-text bg-gradient-to-r from-[#ba34d5] to-[#33e1b5]'>
            L'Architecte Système
          </span>
        </h2>

        <p class='text-xl text-neutral-300 italic mb-12 border-l-4 border-[#ba34d5] pl-6 py-2'>
          « Je transmute votre chaos opérationnel en un algorithme de haute fréquence, où la précision de l'ingénieur et la clarté du sage fusionnent pour faire de votre entreprise le prolongement fluide de votre conscience. »
        </p>

        <div class='space-y-8'>
          <!-- Pillar 1 -->
          <div class='flex gap-6 p-6 rounded-2xl bg-white/5 backdrop-blur-xl border border-white/10 hover:border-[#ba34d5]/50 transition-colors'>
            <div class='flex-shrink-0 w-12 h-12 rounded-full bg-[#ba34d5]/20 flex items-center justify-center text-[#ba34d5]'>
              <svg xmlns='http://www.w3.org/2000/svg' class='w-6 h-6' fill='none' viewBox='0 0 24 24' stroke='currentColor'><path stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4' /></svg>
            </div>
            <div>
              <h4 class='text-white text-xl font-bold mb-2'>L'Ingénieur</h4>
              <p class='text-neutral-400'>Nettoyage du "legacy code" de vos systèmes pour supprimer la friction technique et fluidifier les processus opérationnels.</p>
            </div>
          </div>

          <!-- Pillar 2 -->
          <div class='flex gap-6 p-6 rounded-2xl bg-white/5 backdrop-blur-xl border border-white/10 hover:border-[#33e1b5]/50 transition-colors'>
            <div class='flex-shrink-0 w-12 h-12 rounded-full bg-[#33e1b5]/20 flex items-center justify-center text-[#33e1b5]'>
              <svg xmlns='http://www.w3.org/2000/svg' class='w-6 h-6' fill='none' viewBox='0 0 24 24' stroke='currentColor'><path stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z' /></svg>
            </div>
            <div>
              <h4 class='text-white text-xl font-bold mb-2'>Le Scientifique</h4>
              <p class='text-neutral-400'>Lecture rigoureuse des patterns et des probabilités pour remplacer l'intuition floue par une stratégie basée sur l'évidence.</p>
            </div>
          </div>

          <!-- Pillar 3 -->
          <div class='flex gap-6 p-6 rounded-2xl bg-white/5 backdrop-blur-xl border border-white/10 hover:border-[#ba34d5]/50 transition-colors'>
            <div class='flex-shrink-0 w-12 h-12 rounded-full bg-[#ba34d5]/20 flex items-center justify-center text-[#ba34d5]'>
              <svg xmlns='http://www.w3.org/2000/svg' class='w-6 h-6' fill='none' viewBox='0 0 24 24' stroke='currentColor'><path stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z' /></svg>
            </div>
            <div>
              <h4 class='text-white text-xl font-bold mb-2'>Le Spirituel</h4>
              <p class='text-neutral-400'>Alignement profond sur l'intention pure (le Why) pour éviter le burn-out de l'âme et transformer la boîte en un organisme conscient.</p>
            </div>
          </div>
        </div>

        <div class='mt-12'>
          <a href='#contact' class='inline-block px-10 py-5 bg-gradient-to-r from-[#ba34d5] to-[#33e1b5] text-white rounded-full font-bold text-lg hover:scale-105 transition-transform shadow-lg shadow-[#ba34d5]/20'>
            Réaligner mon système
          </a>
        </div>
      </div>
    </div>
  </div>
</section>` }} />
         

         <div id="services" dangerouslySetInnerHTML={{ __html: `<section id='services' class='bg-neutral-950 text-white py-32 lg:py-48 overflow-hidden'>
  <div class='container mx-auto px-6 relative'>
    <!-- Background Decorative Element -->
    <div class='absolute top-0 -left-20 w-96 h-96 bg-[#ba34d5]/10 rounded-full blur-[120px] pointer-events-none'></div>
    <div class='absolute bottom-0 -right-20 w-96 h-96 bg-[#33e1b5]/10 rounded-full blur-[120px] pointer-events-none'></div>

    <!-- Section Header -->
    <div class='max-w-4xl mx-auto text-center mb-24 relative z-10'>
      <span class='text-[#33e1b5] font-medium tracking-[0.3em] uppercase text-sm mb-6 block'>L'Alchimie de la Performance</span>
      <h2 class='text-5xl md:text-7xl font-serif mb-8 text-transparent bg-clip-text bg-gradient-to-r from-[#ba34d5] to-[#33e1b5] leading-tight'>
        La Méthode d'Ingénierie de la Conscience
      </h2>
      <div class='w-24 h-1 bg-gradient-to-r from-[#ba34d5] to-[#33e1b5] mx-auto mb-10'></div>
      <p class='text-xl md:text-2xl text-neutral-300 leading-relaxed font-light italic opacity-90'>
        « Je transmute votre chaos opérationnel en un algorithme de haute fréquence, où la précision de l'ingénieur et la clarté du sage fusionnent pour faire de votre entreprise le prolongement fluide de votre conscience. »
      </p>
    </div>

    <!-- Services Grid -->
    <div class='grid grid-cols-1 lg:grid-cols-3 gap-8 relative z-10'>
      
      <!-- Pillar 1: Engineering -->
      <div class='group p-10 rounded-3xl bg-white/5 backdrop-blur-xl border border-white/10 hover:border-[#ba34d5]/50 transition-all duration-500 transform hover:-translate-y-2'>
        <div class='w-16 h-16 mb-8 flex items-center justify-center rounded-2xl bg-gradient-to-br from-[#ba34d5]/20 to-transparent border border-[#ba34d5]/30'>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 text-[#ba34d5]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
          </svg>
        </div>
        <h3 class='text-2xl font-serif mb-4 text-white group-hover:text-[#ba34d5] transition-colors'>L'Ingénieur : Refactoring Systémique</h3>
        <p class='text-neutral-400 leading-relaxed'>
          Nous nettoyons le <span class='text-white font-medium'>"legacy code"</span> de vos systèmes. En identifiant et en supprimant la friction technique, nous transformons votre structure rigide en un moteur fluide capable d'encaisser la croissance sans casser.
        </p>
      </div>

      <!-- Pillar 2: Science -->
      <div class='group p-10 rounded-3xl bg-white/5 backdrop-blur-xl border border-white/10 hover:border-[#33e1b5]/50 transition-all duration-500 transform hover:-translate-y-2'>
        <div class='w-16 h-16 mb-8 flex items-center justify-center rounded-2xl bg-gradient-to-br from-[#33e1b5]/20 to-transparent border border-[#33e1b5]/30'>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 text-[#33e1b5]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
          </svg>
        </div>
        <h3 class='text-2xl font-serif mb-4 text-white group-hover:text-[#33e1b5] transition-colors'>Le Scientifique : Neuro-performance</h3>
        <p class='text-neutral-400 leading-relaxed'>
          Remplacez l'intuition floue par une <span class='text-white font-medium'>lecture rigoureuse des patterns</span>. Nous analysons les probabilités et vos schémas décisionnels pour optimiser vos fonctions cognitives et votre capacité à piloter dans l'incertitude.
        </p>
      </div>

      <!-- Pillar 3: Spiritual -->
      <div class='group p-10 rounded-3xl bg-white/5 backdrop-blur-xl border border-white/10 hover:border-white/40 transition-all duration-500 transform hover:-translate-y-2'>
        <div class='w-16 h-16 mb-8 flex items-center justify-center rounded-2xl bg-gradient-to-br from-white/10 to-transparent border border-white/20'>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364-6.364l-.707.707M6.343 17.657l-.707.707m12.728 0l-.707-.707M6.343 6.343l-.707-.707m12.728 0A9 9 0 115.636 5.636m12.728 12.728A9 9 0 015.636 18.364" />
          </svg>
        </div>
        <h3 class='text-2xl font-serif mb-4 text-white transition-colors'>Le Spirituel : Alignement de Fréquence</h3>
        <p class='text-neutral-400 leading-relaxed'>
          S'assurer que le moteur ne tourne pas à vide. Nous reconnectons votre croissance à votre <span class='text-white font-medium'>Intention Pure (le Why)</span>, évitant ainsi le burn-out de l'âme pour un succès qui nourrit autant qu'il rapporte.
        </p>
      </div>

    </div>

    <!-- Conclusion CTA -->
    <div class='mt-24 text-center max-w-3xl mx-auto'>
      <p class='text-xl text-neutral-300 mb-10 leading-relaxed'>
        Ne vous contentez plus de "gérer" une boîte. Devenez le <span class='text-[#33e1b5] font-semibold'>système d'exploitation conscient</span> d'un organisme qui génère de la valeur sans effort superflu.
      </p>
      <a href='#contact' class='inline-block px-12 py-5 bg-gradient-to-r from-[#ba34d5] to-[#33e1b5] text-white font-bold rounded-full text-lg shadow-[0_10px_40px_-10px_rgba(186,52,213,0.5)] hover:shadow-[0_20px_50px_-10px_rgba(186,52,213,0.7)] transition-all duration-300 transform hover:-translate-y-1'>
        Initialiser ma Transformation
      </a>
    </div>
  </div>
</section>` }} />
         

         <div id="how_it_works" dangerouslySetInnerHTML={{ __html: `<section class="relative bg-neutral-950 text-white py-32 lg:py-48 overflow-hidden font-['Playfair_Display']">
  <!-- Background Orbs -->
  <div class="absolute top-0 left-1/4 w-96 h-96 bg-[#ba34d5]/10 rounded-full blur-[120px] pointer-events-none"></div>
  <div class="absolute bottom-0 right-1/4 w-96 h-96 bg-[#33e1b5]/10 rounded-full blur-[120px] pointer-events-none"></div>

  <div class="container mx-auto px-6 relative z-10">
    <!-- Header -->
    <div class="max-w-4xl mb-24">
      <h2 class="text-4xl md:text-6xl font-bold leading-tight mb-8">
        Votre Parcours de <span class="text-transparent bg-clip-text bg-gradient-to-r from-[#ba34d5] to-[#33e1b5]">Transformation</span>
      </h2>
      <p class="text-xl md:text-2xl text-neutral-400 max-w-2xl leading-relaxed">
        Une alchimie entre rigueur scientifique et clarté spirituelle pour transmuter votre chaos opérationnel en un algorithme de haute fréquence.
      </p>
    </div>

    <!-- Steps Grid -->
    <div class="grid lg:grid-cols-3 gap-8">
      
      <!-- Step 1 -->
      <div class="group relative">
        <div class="absolute -inset-1 bg-gradient-to-b from-[#ba34d5] to-transparent opacity-0 group-hover:opacity-20 transition duration-500 rounded-[2.5rem]"></div>
        <div class="relative h-full bg-white/5 backdrop-blur-xl border border-white/10 p-10 rounded-[2.5rem] transition-transform duration-500 group-hover:-translate-y-2">
          <span class="inline-block text-sm font-bold tracking-[0.2em] text-[#ba34d5] mb-6 uppercase">Étape 01 — L'Ingénieur</span>
          <h3 class="text-3xl font-semibold mb-6">Le Questionnaire de Fréquence</h3>
          <p class="text-neutral-400 leading-relaxed mb-8">
            Nous isolons les variables de friction et nettoyons le "legacy code" de vos systèmes. Une analyse chirurgicale pour identifier où l'énergie de votre entreprise s'évapore inutilement.
          </p>
          <div class="w-12 h-12 flex items-center justify-center rounded-full bg-white/5 border border-white/20">
            <svg class="w-6 h-6 text-[#ba34d5]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
          </div>
        </div>
      </div>

      <!-- Step 2 -->
      <div class="group relative">
        <div class="absolute -inset-1 bg-gradient-to-b from-[#33e1b5] to-transparent opacity-0 group-hover:opacity-20 transition duration-500 rounded-[2.5rem]"></div>
        <div class="relative h-full bg-white/5 backdrop-blur-xl border border-white/10 p-10 rounded-[2.5rem] transition-transform duration-500 group-hover:-translate-y-2">
          <span class="inline-block text-sm font-bold tracking-[0.2em] text-[#33e1b5] mb-6 uppercase">Étape 02 — Le Scientifique</span>
          <h3 class="text-3xl font-semibold mb-6">Le Rapport d'Audit Flash</h3>
          <p class="text-neutral-400 leading-relaxed mb-8">
            Le chaos devient data. Nous remplaçons l'intuition floue par une lecture rigoureuse des patterns et des probabilités pour cartographier vos points de rupture émotionnels et opérationnels.
          </p>
          <div class="w-12 h-12 flex items-center justify-center rounded-full bg-white/5 border border-white/20">
            <svg class="w-6 h-6 text-[#33e1b5]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M13 10V3L4 14h7v7l9-11h-7z"></path></svg>
          </div>
        </div>
      </div>

      <!-- Step 3 -->
      <div class="group relative">
        <div class="absolute -inset-1 bg-gradient-to-b from-white to-transparent opacity-0 group-hover:opacity-10 transition duration-500 rounded-[2.5rem]"></div>
        <div class="relative h-full bg-white/5 backdrop-blur-xl border border-white/10 p-10 rounded-[2.5rem] transition-transform duration-500 group-hover:-translate-y-2">
          <span class="inline-block text-sm font-bold tracking-[0.2em] text-white/60 mb-6 uppercase">Étape 03 — Le Sage</span>
          <h3 class="text-3xl font-semibold mb-6">Session de Mapping Initiale</h3>
          <p class="text-neutral-400 leading-relaxed mb-8">
            L'alignement final. Nous nous assurons que votre moteur de croissance est alimenté par une intention pure, évitant le burn-out de l'âme pour faire de votre business un organisme fluide.
          </p>
          <div class="w-12 h-12 flex items-center justify-center rounded-full bg-white/5 border border-white/20">
            <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z"></path></svg>
          </div>
        </div>
      </div>

    </div>

    <!-- Bottom Quote -->
    <div class="mt-24 pt-12 border-t border-white/5 flex flex-col md:flex-row items-center justify-between gap-8">
      <p class="italic text-neutral-500 text-lg">
        "Devenez le système d'exploitation conscient de votre propre organisme."
      </p>
      <a href="#" class="group relative inline-flex items-center px-12 py-5 rounded-full overflow-hidden">
        <span class="absolute inset-0 bg-gradient-to-r from-[#ba34d5] to-[#33e1b5]"></span>
        <span class="absolute inset-0 bg-black opacity-0 group-hover:opacity-10 transition-opacity duration-300"></span>
        <span class="relative font-bold text-white">Commencer mon audit</span>
        <svg class="relative w-5 h-5 ml-3 transition-transform duration-300 group-hover:translate-x-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14 5l7 7m0 0l-7 7m7-7H3"></path></svg>
      </a>
    </div>
  </div>
</section>` }} />
         

         <div id="faq" dangerouslySetInnerHTML={{ __html: `<section class="relative bg-neutral-950 py-32 md:py-48 overflow-hidden" style="font-family: 'Playfair Display', serif;">
  <!-- Background Orbs for Depth -->
  <div class="absolute top-1/4 -left-20 w-96 h-96 bg-[#ba34d5]/10 rounded-full blur-[120px] pointer-events-none"></div>
  <div class="absolute bottom-1/4 -right-20 w-96 h-96 bg-[#33e1b5]/10 rounded-full blur-[120px] pointer-events-none"></div>

  <div class="container mx-auto px-6 relative z-10">
    <div class="max-w-4xl mx-auto mb-20 text-center">
      <h2 class="text-5xl md:text-7xl font-bold mb-8 text-transparent bg-clip-text bg-gradient-to-r from-[#ba34d5] to-[#33e1b5]">
        Questions Fréquentes
      </h2>
      <p class="text-xl md:text-2xl text-white leading-relaxed font-light opacity-90">
        Démystifier l'alchimie entre la rigueur de l'ingénieur et la clarté du sage pour propulser votre croissance.
      </p>
    </div>

    <div class="max-w-4xl mx-auto space-y-6">
      <!-- FAQ Item 1 -->
      <div class="group border border-white/10 bg-white/5 backdrop-blur-xl rounded-3xl p-8 transition-all duration-500 hover:border-[#ba34d5]/50">
        <div class="flex justify-between items-center gap-6">
          <h3 class="text-2xl font-bold text-white">Est-ce une approche purement « spirituelle » ou concrète ?</h3>
          <div class="text-[#33e1b5] group-hover:rotate-45 transition-transform duration-300">
            <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M12 4v16m8-8H4"/></svg>
          </div>
        </div>
        <div class="mt-6 text-neutral-400 leading-relaxed text-lg">
          C’est la fusion des deux. L’approche spirituelle sans rigueur est un rêve éveillé ; la rigueur sans âme est une cage dorée. Je nettoie votre « legacy code » opérationnel (Ingénieur) et j'utilise la science des probabilités pour supprimer la friction, tout en m'assurant que votre moteur de croissance est alimenté par une intention pure.
        </div>
      </div>

      <!-- FAQ Item 2 -->
      <div class="group border border-white/10 bg-white/5 backdrop-blur-xl rounded-3xl p-8 transition-all duration-500 hover:border-[#33e1b5]/50">
        <div class="flex justify-between items-center gap-6">
          <h3 class="text-2xl font-bold text-white">Quel est le retour sur investissement de l'alignement interne ?</h3>
          <div class="text-[#ba34d5] group-hover:rotate-45 transition-transform duration-300">
            <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M12 4v16m8-8H4"/></svg>
          </div>
        </div>
        <div class="mt-6 text-neutral-400 leading-relaxed text-lg">
          Le chaos opérationnel est une taxe invisible sur vos profits. En transmutant ce chaos en un algorithme de haute fréquence, vous éliminez les erreurs coûteuses, accélérez vos cycles de décision et évitez le burn-out de l'âme. Vous ne gérez plus une boîte ; vous devenez le système d'exploitation d'un organisme qui génère de la valeur avec une fluidité déconcertante.
        </div>
      </div>

      <!-- FAQ Item 3 -->
      <div class="group border border-white/10 bg-white/5 backdrop-blur-xl rounded-3xl p-8 transition-all duration-500 hover:border-[#ba34d5]/50">
        <div class="flex justify-between items-center gap-6">
          <h3 class="text-2xl font-bold text-white">Comment la science aide-t-elle à lever des blocages émotionnels ?</h3>
          <div class="text-[#33e1b5] group-hover:rotate-45 transition-transform duration-300">
            <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M12 4v16m8-8H4"/></svg>
          </div>
        </div>
        <div class="mt-6 text-neutral-400 leading-relaxed text-lg">
          La science remplace l'intuition floue par une lecture rigoureuse des patterns. En identifiant les répétitions systémiques dans votre entreprise et votre vie, nous extrayons des données objectives là où vous ne voyez que du stress. Cela nous permet de cibler le « bug » émotionnel précis qui bloque la machine, plutôt que de traiter les symptômes superficiels.
        </div>
      </div>

      <!-- FAQ Item 4 -->
      <div class="group border border-white/10 bg-white/5 backdrop-blur-xl rounded-3xl p-8 transition-all duration-500 hover:border-[#33e1b5]/50">
        <div class="flex justify-between items-center gap-6">
          <h3 class="text-2xl font-bold text-white">À qui s'adresse cette transformation « ultime » ?</h3>
          <div class="text-[#ba34d5] group-hover:rotate-45 transition-transform duration-300">
            <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M12 4v16m8-8H4"/></svg>
          </div>
        </div>
        <div class="mt-6 text-neutral-400 leading-relaxed text-lg">
          Elle est réservée aux entrepreneurs qui ont déjà bâti un système mais qui sentent qu'ils ont atteint un plafond de verre de complexité. Si vous avez le sentiment que votre entreprise tourne à vide ou qu'elle ne résonne plus avec votre Why profond, mon rôle est de réaligner l'architecture complète pour qu'elle devienne le prolongement fluide de votre conscience.
        </div>
      </div>
    </div>

    <div class="mt-20 text-center">
      <a href="#contact" class="inline-block px-12 py-5 rounded-full bg-gradient-to-r from-[#ba34d5] to-[#33e1b5] text-white font-bold text-lg hover:scale-105 transition-transform duration-300 shadow-[0_0_40px_rgba(186,52,213,0.3)]">
        Clarifier ma Vision
      </a>
    </div>
  </div>
</section>` }} />
         

         <div id="contact_form" dangerouslySetInnerHTML={{ __html: `<section class="relative bg-neutral-950 text-white py-32 lg:py-48 overflow-hidden font-['Playfair_Display']">
  <!-- Decorative background elements -->
  <div class="absolute top-0 right-0 -translate-y-1/2 translate-x-1/3 w-[600px] h-[600px] bg-[#ba34d5]/10 rounded-full blur-[120px] pointer-events-none"></div>
  <div class="absolute bottom-0 left-0 translate-y-1/2 -translate-x-1/3 w-[500px] h-[500px] bg-[#33e1b5]/10 rounded-full blur-[100px] pointer-events-none"></div>

  <div class="container mx-auto px-6 relative z-10">
    <div class="grid lg:grid-cols-2 gap-16 lg:gap-24 items-center">
      
      <!-- Narrative Column -->
      <div>
        <h2 class="text-4xl md:text-5xl lg:text-6xl font-bold leading-tight mb-8">
          <span class="text-transparent bg-clip-text bg-gradient-to-r from-[#ba34d5] to-[#33e1b5]">
            Initier votre Scan de Cohérence
          </span>
        </h2>
        <p class="text-xl text-neutral-300 mb-12 max-w-xl font-light leading-relaxed">
          Formulaire sécurisé pour quitter le bruit et entrer dans la précision chirurgicale de votre nouvelle architecture entrepreneuriale.
        </p>

        <div class="space-y-8">
          <div class="flex gap-6 items-start">
            <div class="flex-shrink-0 w-12 h-12 rounded-2xl bg-white/5 border border-white/10 flex items-center justify-center">
              <svg class="w-6 h-6 text-[#ba34d5]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"></path></svg>
            </div>
            <div>
              <h4 class="text-lg font-semibold mb-2 italic">L'Ingénieur</h4>
              <p class="text-neutral-400 text-sm leading-relaxed">Nettoyage du "legacy code" de vos systèmes pour supprimer définitivement la friction technique.</p>
            </div>
          </div>

          <div class="flex gap-6 items-start">
            <div class="flex-shrink-0 w-12 h-12 rounded-2xl bg-white/5 border border-white/10 flex items-center justify-center">
              <svg class="w-6 h-6 text-[#33e1b5]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"></path></svg>
            </div>
            <div>
              <h4 class="text-lg font-semibold mb-2 italic">Le Scientifique</h4>
              <p class="text-neutral-400 text-sm leading-relaxed">Remplacement de l'intuition floue par une lecture rigoureuse des patterns et des probabilités.</p>
            </div>
          </div>

          <div class="flex gap-6 items-start">
            <div class="flex-shrink-0 w-12 h-12 rounded-2xl bg-white/5 border border-white/10 flex items-center justify-center">
              <svg class="w-6 h-6 text-[#ba34d5]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"></path></svg>
            </div>
            <div>
              <h4 class="text-lg font-semibold mb-2 italic">Le Spirituel</h4>
              <p class="text-neutral-400 text-sm leading-relaxed">Alignement du moteur de croissance sur une intention pure pour éviter le burn-out de l'âme.</p>
            </div>
          </div>
        </div>
      </div>

      <!-- Form Column -->
      <div class="relative">
        <div class="absolute -inset-1 bg-gradient-to-r from-[#ba34d5] to-[#33e1b5] rounded-[2.5rem] blur opacity-20"></div>
        <div class="relative bg-white/5 backdrop-blur-2xl border border-white/10 p-8 md:p-12 rounded-[2.5rem] shadow-2xl">
          <form action="#" class="space-y-6">
            <div class="space-y-2">
              <label class="text-xs uppercase tracking-widest text-[#33e1b5] font-bold ml-1">Identité Consciente</label>
              <input type="text" placeholder="Nom complet" class="w-full bg-white/5 border border-white/10 rounded-2xl py-4 px-6 focus:border-[#ba34d5] focus:ring-1 focus:ring-[#ba34d5] outline-none transition-all placeholder:text-neutral-600" />
            </div>
            
            <div class="space-y-2">
              <label class="text-xs uppercase tracking-widest text-[#33e1b5] font-bold ml-1">Fréquence Numérique</label>
              <input type="email" placeholder="votre@email.com" class="w-full bg-white/5 border border-white/10 rounded-2xl py-4 px-6 focus:border-[#ba34d5] focus:ring-1 focus:ring-[#ba34d5] outline-none transition-all placeholder:text-neutral-600" />
            </div>

            <div class="space-y-2">
              <label class="text-xs uppercase tracking-widest text-[#33e1b5] font-bold ml-1">Analyse du Chaos Actuel</label>
              <textarea rows="4" placeholder="Décrivez les frictions qui ralentissent votre expansion..." class="w-full bg-white/5 border border-white/10 rounded-2xl py-4 px-6 focus:border-[#ba34d5] focus:ring-1 focus:ring-[#ba34d5] outline-none transition-all placeholder:text-neutral-600 resize-none"></textarea>
            </div>

            <button type="submit" class="w-full group relative flex items-center justify-center py-5 px-8 rounded-2xl font-bold text-lg overflow-hidden transition-all duration-300">
              <div class="absolute inset-0 bg-gradient-to-r from-[#ba34d5] to-[#33e1b5] transition-transform group-hover:scale-105"></div>
              <span class="relative flex items-center gap-2">
                Transmuter mon Architecture
                <svg class="w-5 h-5 group-hover:translate-x-1 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3"></path></svg>
              </span>
            </button>

            <p class="text-center text-[10px] text-neutral-500 uppercase tracking-tighter">
              Données sécurisées • Traitement confidentiel • Haute Fréquence
            </p>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>` }} />
         

         <div id="footer" dangerouslySetInnerHTML={{ __html: `<footer class="bg-neutral-950 text-white font-serif border-t border-white/10 pt-24 pb-12">
  <div class="container mx-auto px-6">
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-16 mb-20">
      
      <!-- Brand & Vision -->
      <div class="lg:col-span-2 space-y-8">
        <h2 class="text-3xl font-bold tracking-tighter">
          <span class="text-transparent bg-clip-text bg-gradient-to-r from-[#ba34d5] to-[#33e1b5]">
            Julien de Alma
          </span>
        </h2>
        <p class="text-lg text-neutral-400 max-w-md leading-relaxed">
          Transmuter votre chaos opérationnel en un algorithme de haute fréquence. Là où la précision de l'ingénieur et la clarté du sage fusionnent pour libérer votre expansion.
        </p>
        <div class="flex space-x-5">
          <a href="#" class="w-12 h-12 rounded-full border border-white/10 flex items-center justify-center bg-white/5 hover:bg-[#ba34d5]/20 hover:border-[#ba34d5] transition-all duration-300 backdrop-blur-xl group">
            <svg class="w-5 h-5 fill-current group-hover:text-[#ba34d5]" viewBox="0 0 24 24"><path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"/></svg>
          </a>
          <a href="#" class="w-12 h-12 rounded-full border border-white/10 flex items-center justify-center bg-white/5 hover:bg-[#33e1b5]/20 hover:border-[#33e1b5] transition-all duration-300 backdrop-blur-xl group">
            <svg class="w-5 h-5 fill-current group-hover:text-[#33e1b5]" viewBox="0 0 24 24"><path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"/></svg>
          </a>
        </div>
      </div>

      <!-- Navigation -->
      <div>
        <h4 class="text-sm font-sans uppercase tracking-[0.2em] mb-8 text-[#33e1b5]">Navigation</h4>
        <ul class="space-y-4 text-neutral-400">
          <li><a href="#" class="hover:text-white transition-colors duration-200">Le Processus</a></li>
          <li><a href="#" class="hover:text-white transition-colors duration-200">L'Ingénierie de l'Âme</a></li>
          <li><a href="#" class="hover:text-white transition-colors duration-200">Accompagnement</a></li>
          <li><a href="#" class="hover:text-white transition-colors duration-200">Contact</a></li>
        </ul>
      </div>

      <!-- Juridique -->
      <div>
        <h4 class="text-sm font-sans uppercase tracking-[0.2em] mb-8 text-[#ba34d5]">Légal</h4>
        <ul class="space-y-4 text-neutral-400">
          <li><a href="#" class="hover:text-white transition-colors duration-200">Mentions Légales</a></li>
          <li><a href="#" class="hover:text-white transition-colors duration-200">Confidentialité</a></li>
          <li><a href="#" class="hover:text-white transition-colors duration-200">CGV</a></li>
          <li><a href="#" class="hover:text-white transition-colors duration-200">Cookies</a></li>
        </ul>
      </div>

    </div>

    <!-- Bottom Bar -->
    <div class="pt-12 border-t border-white/5 flex flex-col md:flex-row justify-between items-center space-y-6 md:space-y-0 text-sm text-neutral-500">
      <div class="flex items-center space-x-2">
        <span>© 2024 Julien de Alma.</span>
        <span class="hidden md:inline text-neutral-700">|</span>
        <span>Alignement. Précision. Expansion.</span>
      </div>
      <div class="flex items-center group">
        <span class="mr-2">Design d'exception par</span>
        <span class="text-white font-medium group-hover:text-[#33e1b5] transition-colors cursor-default">Alma Studio</span>
      </div>
    </div>
  </div>
</footer>` }} />
         
    </main>
  );
}
